name: family_ledger
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.0
  - click>=8.1
  - pyyaml>=6.0
  - pip  # keeps pip available for anything not yet on conda
  - pip:
      - pdfplumber>=0.11.4